#!/usr/bin/env python3
"""
gen_revision_table.py -- the per-revision table, generated, never typed.

The reviewer asked for a table covering each revision boundary. numbers.json
already records everything it needs: for every candidate cut, the byte offset,
which signatures survive, how many document timestamps survive, whether the
truncated file is byte-identical to the legitimately signed inner document,
and whether a surviving timestamp still covers the whole remaining file.

This writes paper/generated/revisions.tex, which the paper \\input{}s the same
way it does numbers.tex. No figure in the table is transcribed by hand, so the
table cannot drift away from the run that produced it -- the failure mode the
artifact was restructured to eliminate.

    python gen_revision_table.py [results/numbers.json]

The decisive row -- the cut that reproduces the legitimately archived
classical-only document byte for byte -- is marked with a dagger and named in
the caption, so a reader can see at a glance which boundary the claim rests on.
"""
import json
import os
import sys


def grp(n):
    """22958 -> 22{,}958, the IEEEtran-safe thousands separator."""
    return f"{n:,}".replace(",", "{,}")


def surviving_label(cut):
    """What a validator would report as still verifying at this cut."""
    sigs = list(cut.get("surviving") or [])
    ts = cut.get("surviving_timestamps")
    if not sigs and not ts:
        return "---"
    parts = []
    for s in sigs:
        parts.append({"ClassicalLayer": "classical",
                      "PQLayer": "post-quantum"}.get(s, s))
    if ts:
        parts.append(f"{ts}$\\times$ timestamp")
    return ", ".join(parts)


def rows_for(order, decisive_index):
    out = []
    for c in order.get("cuts") or []:
        if not c.get("valid_document"):
            outcome = "not a valid document"
        else:
            who = ("classical only" if c.get("classical_only")
                   else "post-quantum only" if c.get("pq_only")
                   else "both layers")
            extra = []
            if c.get("timestamp_entire_file"):
                extra.append("timestamp covers file")
            if c.get("identical_to_inner"):
                extra.append("\\textbf{byte-identical}")
            outcome = who + (", " + ", ".join(extra) if extra else "")
        out.append({"index": c["index"], "offset": grp(c["offset"]),
                    "outcome": outcome,
                    "mark": "$\\dagger$" if c.get("identical_to_inner") else ""})
    return out


def emit_table(f, label, caption, rows):
    f.write("\\begin{table}[!t]\n\\centering\n")
    f.write(f"\\caption{{{caption}}}\n\\label{{{label}}}\n")
    f.write("\\footnotesize\n")
    f.write("\\begin{tabular}{@{}rrl@{}}\n\\toprule\n")
    f.write("Cut & Offset (B) & Outcome \\\\\n\\midrule\n")
    for r in rows:
        f.write(f"{r['index']}{r['mark']} & {r['offset']} "
                f"& {r['outcome']} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n\n")


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        "results", "numbers.json")
    with open(src, encoding="utf-8") as fh:
        d = json.load(fh)

    out_dir = os.path.join("paper", "generated")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "revisions.tex")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("% revisions.tex -- GENERATED by gen_revision_table.py.\n")
        f.write("% Do not edit by hand; regenerate after every run_all.py.\n")
        f.write(f"% source: {os.path.basename(src)}, "
                f"run {(d.get('meta') or {}).get('generated')}\n\n")

        for exp, human in (("E2", "PAdES-B-LTA"),):
            e = d.get(exp)
            if not e:
                continue
            for order, desc in (("A", "order A (classical inner, "
                                      "post-quantum outer)"),):
                x = (e.get("orders") or {}).get(order)
                if not x:
                    continue
                rows = rows_for(x, None)
                classical_only = x.get("cuts_classical_only", 0)
                pq_only = x.get("cuts_pq_only", 0)
                if order == "A":
                    tail = (f"{classical_only} of the {x['cut_points']} cuts leave a "
                            "document carrying the classical signature with no "
                            "post-quantum evidence at all")
                else:
                    tail = (f"no cut leaves a classical-only document; "
                            f"{pq_only} leave{'s' if pq_only == 1 else ''} the "
                            f"post-quantum layer instead")
                cap = (f"Every truncation point of the {human} document, "
                       f"{desc}. {tail}. "
                       "$\\dagger$ marks the cut whose output is byte-identical "
                       "to the legitimately signed inner document.")
                emit_table(f, f"tab:rev{exp}{order}", cap, rows)

    print(f"wrote {out_path}")
    with open(out_path, encoding="utf-8") as fh:
        n = sum(1 for line in fh if line.rstrip().endswith("\\\\"))
    print(f"  {n} table rows generated")


if __name__ == "__main__":
    main()
