"""
Where things live. Every generated byte goes under results/, never next to the
source, so that a clean checkout plus one `run_all.py` reproduces the whole
paper and `results/` can be deleted without losing code.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

PAPER = os.path.join(ROOT, "paper")
GENERATED = os.path.join(PAPER, "generated")          # numbers.tex lands here
RESULTS = os.path.join(ROOT, "results")
ARTIFACTS = os.path.join(RESULTS, "artifacts")        # PDFs, PEMs, cut files


def ensure():
    for d in (RESULTS, ARTIFACTS, GENERATED):
        os.makedirs(d, exist_ok=True)


def art(name):
    """Path to a generated artifact."""
    ensure()
    return os.path.join(ARTIFACTS, name)


def result(name):
    ensure()
    return os.path.join(RESULTS, name)
